# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - microfrontendapp

on:
  push:
    paths-ignore: 
    - '!about/**'
    - '!shared-lib/**'      
    paths:
    - 'appshell/**'
    branches:
      - master
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
          npm install -g piral-cli
          piral build
      working-directory: 'appshell/'
      

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'microfrontendapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e69efef6671f4605a7ad301344fecb47 }}
        package: .
